# Generated by Django 5.1.1 on 2024-09-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe'), ('Van', 'Van'), ('Suv', 'Suv')], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=100),
        ),
    ]
