# Generated by Django 5.1.1 on 2024-11-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_alter_car_condition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name']},
        ),
    ]
