# Generated by Django 5.1.1 on 2024-09-22 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_title', models.CharField(default='Unknown Car', max_length=255)),
                ('first_name', models.CharField(default='youssef', max_length=100)),
                ('last_name', models.CharField(default='baataoui', max_length=100)),
                ('customer_need', models.CharField(default="I'd like to know your best price for this", max_length=255)),
                ('city', models.CharField(default='Orlando', max_length=100)),
                ('state', models.CharField(default='FL', max_length=100)),
                ('email', models.EmailField(default='youssefcar@gmail.com', max_length=254)),
                ('phone', models.CharField(blank=True, default='555 555 5555', max_length=15, null=True)),
                ('message', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
