# Generated by Django 5.1.1 on 2024-09-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='car_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='customer_need',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
