# Generated by Django 5.1.1 on 2024-10-09 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0004_alter_car_condition'),
        ('inquiries', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Car.car'),
        ),
    ]
