# Generated by Django 5.1.1 on 2024-10-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_alter_message_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default='test', max_length=255),
        ),
    ]
