# Generated by Django 5.1.1 on 2024-09-24 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
        ('inquiries', '0004_remove_inquiry_car_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Car.car'),
        ),
    ]
