# Generated by Django 5.1.1 on 2024-10-10 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0005_alter_message_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
